### ISSUE TITLE
Firefox v57.0

### ISSUE THREAD

**Issue by GreenWoodie** [mozfreddyb/webext-firstpartyisolation#1]
Any reason why this extension works in v59 (Nightly 64bit) but not in v57 (stable 64bit) under Windows 10? I can manually set **_privacy.firstparty.isolate_** but the extension doesn't flip it in v57 as it does in v59, Doesn't turn red either so it looks like extension not active rather than just not bit flipping?

Otherwise, interesting extension. Thank you.

**Comment by Aymkdn** [comment]
I can confirm that the fishbowl is grayed out into Firefox v57. So I'm not sure if the extension is working or not...

**Comment by wjladams** [comment]
Same behavior of v57 on mac.

**Comment by rugk** [comment]
I can confirm this behavior, maybe FF 57 did not have the WebExtensions APIs allowing the addon to switch the setting `privacy.firstparty.isolate`?

**Comment by laedit** [comment]
According to the [documentation page](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/privacy#Browser_compatibility), this setting is only available since Firefox 58.
The extension should indicate that the minimum version of Firefox is 58.0.

**Comment by mozfreddyb** [comment]
Apologies. There's a bug in addons.mozilla.org that shows all web extensions as "supported by Firefox 57", which is a tag that I can not remove. What @laedit says is correct though, the *extension API* to change the pref using an extension is for Firefox 58 and older. Users of previous versions of Firefox can change the pref manually in `about:config` of course.
