### ISSUE TITLE
[feature suggestion] FF65+ include privacy.firstparty.isolate.block_post_message

### ISSUE THREAD

**Issue by n8v8R** [mozfreddyb/webext-firstpartyisolation#12]
https://github.com/ghacksuserjs/ghacks-user.js/commit/afee555045df337d07874cf143bdbeaac4c8e363

**Comment by mozfreddyb** [comment]
Thank you for suggesting this feature.
Unfortunately, [this Setting is not within the APIs that Firefox exposes to Web Extensions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy/websites)
