### ISSUE TITLE
cannot login to DKB.de banking with first party isolation

### ISSUE THREAD

**Issue by TjrGithub** [mozfreddyb/webext-firstpartyisolation#20]
Hi,
when First Party Isolation is enabled, I can't login into the online banking with DKB.de:
https://www.dkb.de/banking/finanzstatus/kontoumsaetze?$event=init

Last week, it still worked. I would love it if FirstPartyIsolation would have some builtin ways to diagnose such a problem, and if unavoidable, turn itself off selectively.

Ubuntu Linux 14.04 LTS 
Firefox 66.0.3
First Party Isolation 1.3.1

security updates applied as of 2019-06-23

**Comment by mozfreddyb** [comment]
Please read through issue #8 (original issue text and all of my comments). It's unlikely I can fix this or let alone detect those issues from the extension.  Sorry!

**Comment by TjrGithub** [comment]
For anybody reading this, it seems DKB have silently fixed their website.
@mozfreddyb Thank you for the detailed explanation and instructions for a workaround.
