### ISSUE TITLE
Chromium support

### ISSUE THREAD

**Issue by beerisgood** [mozfreddyb/webext-firstpartyisolation#21]
Is their a way you can port this to Chromium?

**Comment by mozfreddyb** [comment]
No, [this is a specific feature that Firefox has implemented](https://www.bleepingcomputer.com/news/software/another-tor-browser-feature-makes-it-into-firefox-first-party-isolation/). It doesn't exist in Chromium source code and there is no extension API in Chromium. There's also no reason to expect Chromium to ever become as privacy-friendly.

If you value privacy, I can recommend you [Switch to Firefox](https://www.mozilla.org/en-US/firefox/switch/). See also in the article in Washington Post "[Goodbye, Chrome: Google’s web browser has become spy software](https://www.washingtonpost.com/technology/2019/06/21/google-chrome-has-become-surveillance-software-its-time-switch/)".

**Comment by beerisgood** [comment]
I already use Firefox but Mozilla make more and more sh**
Also Vivaldi doesn't look bad with Privacy and chrome/ Chromium have much better security

But okay, sad this API is Firefox only

**Comment by mozfreddyb** [comment]
This comment is to remind everyone, that this is a forum for technical issues with the add-on. Not a discussion forum. Please keep your comments courteous and on topic.
