### ISSUE TITLE
Need a test for the user to make sure the addon is working

### ISSUE THREAD

**Issue by woctezuma** [mozfreddyb/webext-firstpartyisolation#3]
I see two reviews on Mozilla Add-Ons. Both point out that the user has no way to make sure the addon is working as advertised. There has to be a test to let the user ensure it is working.

**Comment by mozfreddyb** [comment]
Oh yes, an FPI test page would be a great idea!
I'll add this to my todo list, albeit with a relatively low priority.
I'm happy to provide hosting & sketch out a development plan if someone's willing to take this on!

**Comment by mozfreddyb** [comment]
https://mozfreddyb.github.io/test-firstpartyisolation/ should work.

Would be great if someone would test and report bugs they find, before I close his issue here. cc @edouard-lopez

**Comment by woctezuma** [comment]
I cannot say much, because:
- the test fails on Internet Explorer,
- the test opens a blank tab on Firefox, without any info printed in the original tab.

![blank tab](https://i.imgur.com/Y5xbKYt.png)

It must be my addons which mess with the webpage.

**Comment by mozfreddyb** [comment]
The test must fail in IE, that's expected.
But the popup tab should be closed automatically...interesting. Do you see any interesting log output in the developer tools (CTRL+SHIFT+K) in either the test page or the opened popup?

**Comment by woctezuma** [comment]
For the test page, nothing.

For the opened popup, which opens in a new tab for me, I get two warnings:
- a warning regarding character encoding,
- a security error.

![popup](https://i.imgur.com/wGPvKUN.png)

**Comment by mozfreddyb** [comment]
I've tested on IE11 and Edge, which should show the correct result. So does Chromium.
I've tested Epiphany as a WebKit browser, for a lack of an actual Safari, but it keeps showing up as FPI enabled, which seems odd. Need to investigate further.

**Comment by mozfreddyb** [comment]
Hm, Firefox Nightly broke some things. Should work again.
Safari/Epiphany still show as "FPI Enabled", which is odd.

**Comment by woctezuma** [comment]
The test is processed fine by my Firefox now.

![pass](https://i.imgur.com/PSy1Omx.png)

I'm not using your addon, but it seems to work. Maybe, it is [Multi-Account Container](https://addons.mozilla.org/firefox/addon/multi-account-containers/).

**Comment by mozfreddyb** [comment]
Could also be Cookie AutoDelete, the test is a bit brittle if you use other privacy-enhancing addons.

**Comment by mozfreddyb** [comment]
I'm thinking of closing this with a patch that points to the test, but I'd be glad if more people tested this before I do so.

**Comment by stoically** [comment]
When deactivating Third-party cookies in the Firefox Preferences the FPS test also reports success.

**Comment by mozfreddyb** [comment]
Yes, I think I could fix this (null with third party cookies disabled,
unequal with FPI).

Hard to make a clear judgement if both.

Can you report this in the repo for the test?

**Comment by stoically** [comment]
Fixing that sounds good!

Sorry, I'm not exactly sure what you mean. Report what and where?

**Comment by mozfreddyb** [comment]
Closing this with a pointer to the issue at the other repository.
