### ISSUE TITLE
Not able to load twitter.com

### ISSUE THREAD

**Issue by the100rabh** [mozfreddyb/webext-firstpartyisolation#30]
Not entirely sure why this is happening to me, but with this extension enabled I am not able to load twitter.com at all. Though interestingly mobile.twitter.com still loads.

**Comment by KevinRoebert** [comment]
Please look at this comment: https://github.com/mozfreddyb/webext-firstpartyisolation/issues/8#issuecomment-370419318

This addon is just a UI for the firefox setting `privacy.firstparty.isolate`. It can't break anything, it is the normal firefox behavior.
