### ISSUE TITLE
YouTube partly broken

### ISSUE THREAD

**Issue by terzag** [mozfreddyb/webext-firstpartyisolation#31]
Hello,
Since today, when trying to view a video on YouTube, the page is only partly displayed: the video is fine but the other parts (top bar with the navigation/options, right column with related videos, comments...) don't load. Disabling the extension makes it work fine, though I had to log-in again (same on other websites), so I assume the issue is related to it.

Using Firefox 81.0 on Ubuntu 20.04.

**Comment by KevinRoebert** [comment]
Please look at this comment: https://github.com/mozfreddyb/webext-firstpartyisolation/issues/8#issuecomment-370419318

This addon is just a UI for the firefox setting `privacy.firstparty.isolate`. It can't break anything, it is the normal firefox behavior.
