### ISSUE TITLE
Is the feature enable?

### ISSUE THREAD

**Issue by edouard-lopez** [mozfreddyb/webext-firstpartyisolation#4]
### Env

> 58.0b5 (64-bit)

### Problem

I'm quoting some review as I met the same issue:
> To echo an earlier review (with better grammar), which mirrored my thought perfectly well: I can't tell if it's enabled or disabled. Clicking its fishbowl icon doesn't visibly change its state; there seems to be no way of knowing if it is working.
> 
> Fix the state notification and then we can review whether it's working as intended... when we actually know it's supposed to be working.

A simple sentence on the button would help:
* FPI enable, click to disable
* FPI disable, click to enable

**Comment by mozfreddyb** [comment]
Yes, thank you for raising this here. Which version of Firefox are you using?

**Comment by edouard-lopez** [comment]
@mozfreddyb updated

**Comment by mozfreddyb** [comment]
I'm not sure I understand. Were/Are you using Firefox 57 or something newer?

**Comment by edouard-lopez** [comment]
I'm using `58.0b5 (64-bit)`, I updated the initial description

**Comment by mozfreddyb** [comment]
Hm, so some background here:
The add-on enables FPI and the icon is grey by default. It turns orange when you click (and if FPI is disabled).
The hover text is "Click to disable" (since enable is default) and "Click to re-enable". This sucks if enabling failed once though. Mh. But I can't think of a scenario in Firefox >58 where the add-on wouldn't be able to set the pref.

**Comment by edouard-lopez** [comment]
Your user interface should tell user what is it's current state:

* feature is disabled, disable the button (grey)
* feature is enabled, enable the button (color)

For example, checkout you wifi icon on android:

![selection_133](https://user-images.githubusercontent.com/1212392/33329345-9e52e910-d45c-11e7-8a64-96deb6088624.png)

**Comment by mozfreddyb** [comment]
Yeah, it usually does that, though with different colors.
The grey I use is taken from all other icons, so the add-on does not stand out too much. It should be orange when disabled.

I'll investigate some more.

**Comment by mozfreddyb** [comment]
Should be fixed. Please file a new issue if your problem persists.
