### ISSUE TITLE
Does FirstPartyIsolation work with Cookie AutoDelete (or the other way around)?

### ISSUE THREAD

**Issue by chrisvdb** [mozfreddyb/webext-firstpartyisolation#6]
I'm trying to use First Party Isolation together with Cookie AutoDelete, but get a warning (most likely generated by Cookie AutoDelete) that both cannot be used together.

Any insight on why both can not or should not be used together?

**Comment by mozfreddyb** [comment]
This should be [fixed](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/266) in Cookie AutoDelete, no?
At least their [release notes](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/blob/378732431b2c5cb6c43299b7f3c4c705a092e0f2/src/ui/settings/ReleaseNotes.json#L7) read to me like this.

**Comment by mozfreddyb** [comment]
@chrisvdb Let me know if that answers your question and what else I can do for you.

**Comment by chrisvdb** [comment]
Ok, thanks, will close this.
