### ISSUE TITLE
Add a whitelist

### ISSUE THREAD

**Issue by barmic** [mozfreddyb/webext-firstpartyisolation#7]
I'm happy with this extension, but atlassian.net (for JIRA) don't work with it ([Atlassian community](https://community.atlassian.com/t5/Jira-questions/cannot-login-with-Firefox-and-privacy-firstparty-isolate-true/qaq-p/701180)).
I'm obliged to disable the extension.

Can we have a white list empty at installation and updatable by user ?

Thank you for your work :)

**Comment by mozfreddyb** [comment]
Sorry, the API by Firefox is a global on/off switch for the whole browser.

**Comment by mozfreddyb** [comment]
I have received a duplicate of this issue and came up with a response that has more context than my previous answer.
It likely still won't fix your problem, but at least there's now a greater explanation of the issue at hand.

Please take a look at issue #8.
